# Generated by Django 5.0.6 on 2024-06-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingmodule",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
