# Generated by Django 5.0.6 on 2024-07-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainee",
            name="designation",
            field=models.CharField(default="Technician", max_length=60),
        ),
    ]
