# Generated by Django 5.0.6 on 2024-07-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0002_trainee_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainee",
            name="Facility",
            field=models.CharField(default="cargo", max_length=15),
        ),
        migrations.AddField(
            model_name="trainee",
            name="Team",
            field=models.CharField(default="Team00", max_length=20),
        ),
    ]
