# Generated by Django 5.0.6 on 2024-06-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0004_alter_trainingmodule_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainingmodule",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
