# Generated by Django 5.0.6 on 2024-06-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Training", "0007_alter_trainingmodule_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="traineeprogress",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="traineeprogress",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
